baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'KOL-ML BLOG'
theme = 'LoveIt'

# 作者配置
[author]
  name = "KOL-ML"
  email = ""
  link = "https://github.com/KenLao1111"

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

# 默认每页列表显示的文章数目
paginate = 12
# 谷歌分析代号 [UA-XXXXXXXX-X]
googleAnalytics = ""
# 版权描述，仅仅用于 SEO
copyright = ""

# 是否使用 robots.txt
enableRobotsTXT = true
# 是否使用 git 信息
enableGitInfo = true
# 是否使用 emoji 代码
enableEmoji = true


# 网站语言, 仅在这里 CN 大写 ["en", "zh-CN", "fr", "pl", ...]
languageCode = "zh-TW"
# 语言名称 ["English", "简体中文", "Français", "Polski", ...]
languageName = "繁體中文"
# 是否包括中日韩文字
hasCJKLanguage = true

# 设置默认的语言 ["en", "zh-cn", "fr", "pl", ...]
defaultContentLanguage = "zh-tw"

[languages]
  [languages.en]
    weight = 1
    title = "KOL-ML BLOG"
    languageCode = "en"
    languageName = "English"
    [[languages.en.menu.main]]
      weight = 1
      identifier = "news"
      pre = ""
      post = ""
      name = "NEWS"
      url = "/news/"
      title = ""
    [[languages.en.menu.main]]
      weight = 2
      identifier = "tags"
      pre = ""
      post = ""
      name = "Tags"
      url = "/tags/"
      title = ""
    [[languages.en.menu.main]]
      weight = 3
      identifier = "categories"
      pre = ""
      post = ""
      name = "Categories"
      url = "/categories/"
      title = ""

  [languages.zh-cn]
    weight = 2
    title = "KOL-ML BLOG"
    languageCode = "zh-TW"
    languageName = "繁體中文"
    hasCJKLanguage = true
    [[languages.zh-cn.menu.main]]
      weight = 1
      identifier = "news"
      pre = ""
      post = ""
      name = "新聞"
      url = "/news/"
      title = ""
    [[languages.zh-cn.menu.main]]
      weight = 2
      identifier = "blogs"
      pre = ""
      post = ""
      name = "網誌"
      url = "/blogs/"
      title = ""
    [[languages.zh-cn.menu.main]]
      weight = 3
      identifier = "categories"
      pre = ""
      post = ""
      name = "分類"
      url = "/categories/"
      title = ""

